# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('shortname', models.CharField(default='', max_length=255)),
                ('cluster', models.CharField(choices=[('ASO', 'ASO'), ('ASPIRE', 'ASPIRE'), ('CAP 12', 'CAP 12'), ('ENGAGE', 'ENGAGE'), ('PROBE', 'PROBE')], default='', max_length=255)),
            ],
        ),
    ]
