# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('term', models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, 'Termlong')], default=0)),
                ('tieupOrgs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostActRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preActs', models.BooleanField()),
                ('listOfExpenses', models.BooleanField()),
                ('gals', models.BooleanField()),
                ('pictures', models.BooleanField()),
                ('actvReport', models.BooleanField()),
                ('evalResults', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='PostActsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('submissionType', models.IntegerField(choices=[(0, 'Not Submitted'), (1, 'Initial Submission'), (2, 'Pended')], default=0)),
                ('enp', models.IntegerField(default=0)),
                ('anp', models.IntegerField(default=0)),
                ('enmp', models.IntegerField(default=0)),
                ('anmp', models.IntegerField(default=0)),
                ('expensesIncurred', models.IntegerField(default=0)),
                ('submittedBy', models.CharField(max_length=255)),
                ('contactNo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(choices=[(0, 'Not Checked'), (1, 'Early Complete'), (2, 'Late Complete'), (3, 'Early Incomplete'), (4, 'Late Incomplete'), (5, 'Acknowledge Cancellation')], default=0)),
                ('checkedBy', models.CharField(max_length=255)),
                ('dateChecked', models.DateTimeField(verbose_name='date checked')),
                ('comments', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Organization'),
        ),
    ]
