# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='', max_length=255)),
                ('value', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostActsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(default=-1)),
                ('timestamp', models.CharField(default='', max_length=255)),
                ('activity_title', models.CharField(default='', max_length=255)),
                ('term', models.CharField(default='', max_length=255)),
                ('organization', models.CharField(default='', max_length=255)),
                ('tie_up_orgs', models.CharField(default='', max_length=255)),
                ('submission_type', models.CharField(default='', max_length=255)),
                ('enp', models.CharField(default='', max_length=255)),
                ('anp', models.CharField(default='', max_length=255)),
                ('enmp', models.CharField(default='', max_length=255)),
                ('anmp', models.CharField(default='', max_length=255)),
                ('expenses_incurred', models.CharField(default='', max_length=255)),
                ('submitted_by', models.CharField(default='', max_length=255)),
                ('contact_no', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('checked_by', models.CharField(blank=True, default='', max_length=255)),
                ('date_checked', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
