# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='term',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('Yearlong', 'Yearlong')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tieupOrgs',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='shortname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='checkedBy',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='contactNo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='expensesIncurred',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='status',
            field=models.CharField(choices=[('EC', 'Early Complete'), ('LC', 'Late Complete'), ('EI', 'Early Incomplete'), ('LI', 'Late Incomplete'), ('AC', 'Acknowledge Cancellation'), ('P', 'Pending')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='submissionType',
            field=models.CharField(choices=[('Initial Submission', 'Initial Submission'), ('Pended', 'Pended')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='submittedBy',
            field=models.CharField(default='', max_length=255),
        ),
    ]
