# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171016_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactslog',
            name='checkedBy',
            field=models.CharField(choices=[('Hordy Mojica', 'Hordy Mojica'), ('Kyle Gecana', 'Kyle Gecana'), ('Nami Inomata', 'Nami Inomata'), ('Jana Josef', 'Jana Josef'), ('Julianne Sy', 'Julianne Sy'), ('Krystel Tan', 'Krystel Tan')], max_length=255),
        ),
    ]
