# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171016_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='shortname',
            field=models.CharField(blank=True, default=models.CharField(default='', max_length=255), max_length=255),
        ),
    ]
