# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171016_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactslog',
            name='checkedBy',
            field=models.CharField(blank=True, choices=[('Hordy Mojica', 'Hordy Mojica'), ('Kyle Gecana', 'Kyle Gecana'), ('Nami Inomata', 'Nami Inomata'), ('Jana Josef', 'Jana Josef'), ('Julianne Sy', 'Julianne Sy'), ('Krystel Tan', 'Krystel Tan')], max_length=255),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='dateChecked',
            field=models.DateTimeField(blank=True, default='', verbose_name='date checked'),
        ),
        migrations.AlterField(
            model_name='postactslog',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Checked'), ('EC', 'Early Complete'), ('LC', 'Late Complete'), ('EI', 'Early Incomplete'), ('LI', 'Late Incomplete'), ('AC', 'Acknowledge Cancellation'), ('P', 'Pending')], default='NC', max_length=255),
        ),
    ]
