# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20171019_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postactslog',
            name='dateChecked',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date checked'),
        ),
    ]
